# Program name.
PROG	=	nc-server

# Don't install it.
NOINST	= 	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva

# Main test code
SRCS	=	main.c
SRCS	+=	simple_server.c

# Data structures
.PATH.c	:	${LIBCPERCIVA_DIR}/datastruct
SRCS	+=	elasticarray.c
SRCS	+=	ptrheap.c
SRCS	+=	timerqueue.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/datastruct

# Event loop
.PATH.c	:	${LIBCPERCIVA_DIR}/events
SRCS	+=	events_immediate.c
SRCS	+=	events_network.c
SRCS	+=	events_network_selectstats.c
SRCS	+=	events_timer.c
SRCS	+=	events.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/events

# Event-driven networking
.PATH.c	:	${LIBCPERCIVA_DIR}/network
SRCS	+=	network_accept.c
SRCS	+=	network_read.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/network

# Utility functions
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	monoclock.c
SRCS	+=	sock.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

.include <bsd.prog.mk>
