# Program name.
PROG	=	nc-server

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# Main test code
SRCS	=	main.c
SRCS	+=	simple_server.c

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/events
IDIRS	+=	-I${LIBCPERCIVA_DIR}/external/queue
IDIRS	+=	-I${LIBCPERCIVA_DIR}/network
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

# spiped includes
IDIRS	+=	-I${LIB_DIR}/util

.include <bsd.prog.mk>
