
all:
	if [ -z "$${HAVE_BUILD_FLAGS}" ]; then \
		cd ${SUBDIR_DEPTH}; \
		${MAKE} BUILD_SUBDIR=${RELATIVE_DIR} \
		    BUILD_TARGET=${PROG} buildsubdir; \
	else \
		${MAKE} ${LIB}; \
	fi

clean:
	rm -f ${LIB} ${SRCS:.c=.o}

${LIB}:${SRCS:.c=.o}
	${AR} ${ARFLAGS} ${LIB} ${SRCS:.c=.o}

