# Program name.
PROG	=	test_pushbits

# Don't install it.
NOINST	=	1

# Library code required
LDADD_REQ	=	-lpthread

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR		=	../../lib
SPIPE_DIR	=	../../spipe

# Main test code
SRCS	=	main.c

# Pushbits
.PATH.c	:	${SPIPE_DIR}
SRCS	+=	pushbits.c
IDIRS	+=	-I${SPIPE_DIR}

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

# spiped includes
IDIRS	+=	-I${LIB_DIR}/util

.include <bsd.prog.mk>
