# Program name.
PROG	=	test_pushbits

# Don't install it.
NOINST	=	1

# Library code required
LDADD_REQ	=	-lpthread

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
SPIPE_DIR	=	../../spipe

# Main test code
SRCS	=	main.c

# Utility functions
SRCS	+=	${LIBCPERCIVA_DIR}/util/getopt.c
SRCS	+=	${LIBCPERCIVA_DIR}/util/noeintr.c
SRCS	+=	${LIBCPERCIVA_DIR}/util/warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

# Pushbits
SRCS	+=	${SPIPE_DIR}/pushbits.c
IDIRS	+=	-I${SPIPE_DIR}

.include <bsd.prog.mk>
