# Program name.
PROG	=	test_pushbits

# Don't install it.
NOINST	=	1

# Library code required
LDADD_REQ =	-lpthread

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
SPIPE_DIR	=	../../spipe

# Main test code
SRCS	=	main.c

# Utility functions
.PATH.c	:	${LIBCPERCIVA_DIR}/util
SRCS	+=	getopt.c
SRCS	+=	noeintr.c
SRCS	+=	warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

# Pushbits
.PATH.c	:	${SPIPE_DIR}
SRCS	+=	pushbits.c
IDIRS	+=	-I${SPIPE_DIR}

.include <bsd.prog.mk>
