# Program name.
PROG	=	recv-zeros

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva

# Main test code
SRCS	=	main.c

# libcperciva includes
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

.include <bsd.prog.mk>
