# Program name.
PROG	=	recv-zeros

# Don't install it.
NOINST	=	1

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva

# Main test code
SRCS	=	main.c

# Utility functions
SRCS	+=	${LIBCPERCIVA_DIR}/util/monoclock.c
SRCS	+=	${LIBCPERCIVA_DIR}/util/sock.c
SRCS	+=	${LIBCPERCIVA_DIR}/util/warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

.include <bsd.prog.mk>
