# Program name.
PROG	=	dnsthread-resolve

# Don't install it.
NOINST	=	1

# Library code required
LDADD_REQ	=	-lpthread

# Useful relative directories
LIBCPERCIVA_DIR	=	../../libcperciva
LIB_DIR	=	../../lib

# Main test code
SRCS	=	main.c

# Data structures
SRCS	+=	${LIBCPERCIVA_DIR}/datastruct/elasticarray.c
SRCS	+=	${LIBCPERCIVA_DIR}/datastruct/ptrheap.c
SRCS	+=	${LIBCPERCIVA_DIR}/datastruct/timerqueue.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/datastruct

# Event loop
SRCS	+=	${LIBCPERCIVA_DIR}/events/events_immediate.c
SRCS	+=	${LIBCPERCIVA_DIR}/events/events_network.c
SRCS	+=	${LIBCPERCIVA_DIR}/events/events_network_selectstats.c
SRCS	+=	${LIBCPERCIVA_DIR}/events/events_timer.c
SRCS	+=	${LIBCPERCIVA_DIR}/events/events.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/events

# Event-driven networking
SRCS	+=	${LIBCPERCIVA_DIR}/network/network_connect.c
SRCS	+=	${LIBCPERCIVA_DIR}/network/network_read.c
SRCS	+=	${LIBCPERCIVA_DIR}/network/network_write.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/network

# Utility functions
SRCS	+=	${LIBCPERCIVA_DIR}/util/asprintf.c
SRCS	+=	${LIBCPERCIVA_DIR}/util/monoclock.c
SRCS	+=	${LIBCPERCIVA_DIR}/util/noeintr.c
SRCS	+=	${LIBCPERCIVA_DIR}/util/sock.c
SRCS	+=	${LIBCPERCIVA_DIR}/util/sock_util.c
SRCS	+=	${LIBCPERCIVA_DIR}/util/warnp.c
IDIRS	+=	-I${LIBCPERCIVA_DIR}/util

# Dnsthread functions
SRCS	+=	${LIB_DIR}/dnsthread/dnsthread.c
IDIRS	+=	-I${LIB_DIR}/dnsthread

.include <bsd.prog.mk>
